### ISSUE TITLE
Conquered Colony not producing

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#112]
I've noticed anti-matter is not stacking and the assemblers are not producing any assembly points on the colony that I captured. Maybe the planet is still in a sort of "occupied" state and therefore not adding any output?

**Comment by Skratti** [comment]
Either the text about "Resistance: 5 turns" is missing, or it isn't red enough

**Comment by marcgfx** [comment]
that would be the explanation. did not see any text :)
