### ISSUE TITLE
Modules not built

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#132]
I just built 4 hyper space engines II + 4 reactor II on Acamar 911
the resources were used but none of the parts appeared :(

**Comment by marcgfx** [comment]
to confirm I also just built a lutetium reactor on the same planet. also missing...

**Comment by marcgfx** [comment]
does not seem to be a problem on other colony. weird

**Comment by marcgfx** [comment]
I think I've found the problem. After the Tick, the metal required for building the modules was back on the transport ships. I'm not sure about the other material.

So what happened: I noticed I could drop off resources over a colony (not the main planet) and this seemed to work just fine. I guess it only worked in the client, not on the server. So my production efforts worked on the client, but there was nothing produced on the server -> no new items in my storage.

**Comment by Skratti** [comment]
As soon as two ships are above a side colony, transfer to the colony is possible. This should not be the case...
