### ISSUE TITLE
Refit Ship Type

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#133]
I am currently refitting a defender-scout to a transporter-fighter. This seems to be working, but in the refit-screen it still shows the scout, but with the modules I removed missing. The stats at the top show the stats of the target vessel.

the things is... this should not really be possible, as otherwise I could simply build scouts and refit them to fregates. this would save a lot of resources.

**Comment by marcgfx** [comment]
I just tried refitting a scout to a fregatte, this actually does not work. So the question is, what is happening with the ship that is actually refitting. the main concern is that it is showing cargo capacity of 580. ship is called T580 and the ID is 650

**Comment by Skratti** [comment]
Client sided, it should not be possible to change the hull during refitting. That change is already not transferred to the server.

Server sided a check is missing, that the transferred module positions (fighter has 6 positions) do exist for the ship hull.

**Comment by Skratti** [comment]
Fixed in the dev environment...
