### ISSUE TITLE
Create Starbase on field with others starbase

### ISSUE THREAD

**Issue by Skratti** [Skratti/EmpiresInSpace#139]
Is not alloed. Does not work.
Message about this is missing...

**Comment by marcgfx** [comment]
I think it should work, as it will cause problems if it does not. It will be hard to make this obvious to players, or will frustrate them with an unexpected error. I think the reason for preventing it was using the space stations for border control?

even if preventing two players from building stations, there will be similar situations.

situation 1: Player A and B are attacking C
Player A deploys space-station over C
Player B embarks space-marines and conquers C
Player B can not build space-stations

situation 2: Player A and B are allies
Player A builds a space-station over B's planet to protect him. 
Player B can not build space-stations

suggestion: Space Stations can always be built
border is not affected by neutral stations over a planet
enemy stations are prioritized in border decisions, the planet has no border control
friendly stations aid the owner of the planet in border growth

**Comment by FlexiGit** [comment]
I think while the stations do not contribute to border, you should simply allow it.

**Comment by Skratti** [comment]
Especially since there is no longer a neutral zone between borders of different factions

**Comment by Skratti** [comment]
fixed and will be deployed asap
