### ISSUE TITLE
transfer of too much results in disappearing modules

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#141]
I was transferring advanced lasers to a space station. the space station did not really have the capacity to take them all, but it worked anyway. I then refitted the space station with the new modules. but I noticed the space station still had the old lasers. also the 4 advanced lasers were no longer on the planet. disaster!

afer reloading I found the lasers still on the planet and reconstructed what had likely happened. this should be prevented by not transferring more than possible in the first place.

**Comment by Skratti** [comment]
Fixed in dev system, will be uploaded asap
