### ISSUE TITLE
Visual Improvements: Modules

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#142]
the visuals make the game very tedious. looking for the advanced laser? oh is it this one, lets mouse-over. nope. this one? ah yes found it. move it to my ship with the laser I on it. go to remove the laser I. is it this one? nope. then it must be the other one... great to have the mouse over not great to have to rely on it.

as you have mentioned before, you could use the colors in the background you also use in the designer.

**Comment by Skratti** [comment]
background colors got implemented
