### ISSUE TITLE
Fleet List Improvements

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#147]
- show planet name, when stationed
- change display for range to Hyper , System / HyperMax , SystemMax it's hard to read now. would be great to have both values next ot each-other
- show health-dot (transition green->yellow->red for damage) HP/MaxHP
- show status (repair, refit)
- cargo (content would be nice, but fill would be good enough) Cargo/MaxCargo

**Comment by Skratti** [comment]
Moved into #124
