### ISSUE TITLE
Scrap Ships and Recycle Modules

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#150]
allow scrapping of ships. return value is 50% of the remaining ship. basically the opposite to repair.
scrap modules by transferring them to a recycle symbol (ship panel, next to planet) also returns 50% of the original value.

**Comment by FlexiGit** [comment]
I strongly support this. Having all this now useless tier 1 junk laying around is pretty bothersome.

**Comment by Skratti** [comment]
Scrapping and recycling is implemented on colonies.
Ships will (for the time being) not be scrappable.
