### ISSUE TITLE
Movement Dots in Space

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#152]
Display the Hyper/System-Drive dot for ships in space. Show the max value for the stacked ships. I often find myself clicking on the same unit again, not knowing if it has already moved.

**Comment by Skratti** [comment]
I'd rather implement a unit management:
- pressing space marks the unit as "done for this turn"
- having no movementpoints marks units as "done"
- left/right arrow switches through ships/fleets that are not "done"
- A sentry mode might also be added

After turn summary, the "done" mark is removed.

**Comment by marcgfx** [comment]
it would not be a replacement for such a system, but a very easy addition based on current tech that would help out until you get to a more complex system )

**Comment by Skratti** [comment]
It's not the same:
The draw routine of the cances would have to draw a circle.
Not that difficult to realize.
But I would try to improve performance while doing so.
Also, currently each ship on a tile is drawn - even if 20 ships stack. that isn't needed, but i'd have to create new images for shipp accumulations...

The dot should perhaps only be drawn for a selected ship - but then other display options are nearly as good.
I'll get out good old heroes 3 and take a look on the movement point display there...

**Comment by marcgfx** [comment]
ah I see, it's canvas not html in space :) ... you could add an html overlay though.
on the other hand drawing a dot should be pretty easy, using a red dot texture. you can then use hue rotation to get other colors.

drawing all  ships makes little sense, I agree. maybe just draw the biggest? so maximum ship + maximum movement points.

the dots would just make sense because of consistency.

**Comment by Skratti** [comment]
One can now  use the new  unit cycling to get to each unit / fleet that still has movement points left.
