### ISSUE TITLE
Stecke in Entwicklungsphase fest =) / Mission übersprungen

### ISSUE THREAD

**Issue by Yademee** [Skratti/EmpiresInSpace#58]
Huhu, ich war schneller als das Tutorial bzw. das Missionsdingbums und kann jetzt nicht mehr bauen außer BM Fabriken und Solarkraftwerke. Natürlich komme ich auch nicht weiter mit der Mission, da der Planet schon kolonisiert ist =D

D.h. ich bin verdammt auf der Zivilisationsstufe einer Prewarpzivilisation.. sniff :dancer: 

Ich bin der Orden von Phyllia =) in dem universum Cygnus A
LG =)

**Comment by Skratti** [comment]
Danke für die Mittteilung.
Ich korrigiere die Daten, und schaue mal ob ich den Fehler reproduzieren
kann...


Am 22. August 2015 um 12:09 schrieb Yademee <notifications@github.com>:
