### ISSUE TITLE
Entering/Exiting Solar System

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#92]
exiting solar systems is actually handled quite nicely, if you know how it works. if you exit it from the bottom, but do so diagonally, you can actually exit the system into the diagonal hypergrid.

entering seems to be a totally different problem. as my system-engines only had little energy left, I entered my planet system from the top, expecting to arrive in the center (giving me enough movement points). but alas I entered 5 fields from the right, what makes no sense to me. I then exited and entered again, wasting some hyperspeed, but still entered at the same point (I has assumed some randomness). My current guess is that I entered closest to the center of my screen, but I don't have any energy to test it.

Mayb allow a player to chose where he enters the system, or make it enter either at the center/corners of the system. otherwise calculating the amount of energy is impossible :(

**Comment by Skratti** [comment]
Randomness in system entry is removed.
