### ISSUE TITLE
battle system balance

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#93]
mein erster kampf, war schon etwas aufschlussreicher. so wie ich sehe werden malus durch schaden erst nach dem kampf aktualisiert. jetzt hast du auch mein schiff gesehen, das war meine überlegung wie ich eine chance gegen holmium haben könnte. ich ging allerdings davon aus, das schaden immer aktualisiert werden würde -> die schweren waffen kommen nach ein paar runden zum tragen. ist aber glaub ich nicht so.

1 vs 1 bei unbeschädigten schiffen wird meines also garantiert verlieren.

ich bin auch überzeugt, wenn es 10 vs 10 wäre, würde ich alle meine schiffe verlieren und du kein einziges, egal wer der angreifer ist.

z.b. erstes schiff von dir greift an 1:0
zwetes schiff greift an 2:0
etc...

meiner meinung nach kein gutes system. auch mit meiner anpassung, reduktion auf 2 kampfrunden wird das problem nicht gelöst. mein schiff könnte aber evtl. vorteile rausholen, wegen den schweren waffen und den beschädigten schiffen die schlechter ausweichen. das kann aber auch der holmium user machen (ich habe auch holmium jetzt)

bei 2 holmium laser (HL) vs 2 normalen lasern (NL) auf vergleichbaren schiffen wird es so ausgehen nach x spielrunden wenn alle immer kämpfen:
NL verliert alle schiffe, HL sind alle beschädigt. vermutlich deutlich weniger beschädigt, als wenn immer alles in einer runde fertig ist. da die NL schneller schaden nehmen und damit schneller weniger schaden anrichten und schneller nicht mehr so gut ausweichen.

das aktuelle kampfsystem bevorteilt stärkere schiffe massiv. hast ja selbst erzählt mit 10 schiffen für eine station... das ist bescheuert :P

so richtig eine gute idee habe ich leider nicht. vieles was ich mir jetzt überlegt habe geht nicht auf. die limitierung auf 2 runden erlaubt aber immerhin das ein spieler sein schiff zurückziehen kann, was ich gut finde. ebenso erlaubt es einen vorteil bei zahlenmässiger überlegenheit. aktuell 3 NL vs 1 HL -> beide verlieren ein schiff. mit meinem vorschlag müsste nur der HL verlieren.

civ funktioniert ja ähnlich, dort haben sie es mit verschiedenen defence boni gelöst.
z.b. könnte man auch hier, über freundlichem gebiet einen defence bonus bekommen von +20%. über einem planeten noch mehr, z.b. +50%.
ebenso könnte man schiffe haben, die auf angriff ausgelegt sind, andere auf defence. das dürfte aber nicht ein modul sein, das platz einnimmt... oder es muss ein spezial-modul sein, das einen eigenen slot hat. oder du hast nen regler, der +25 offensive mit -25% defensive ausgleicht.

**Comment by Skratti** [comment]
Some changes regarding "fair" combat were made:
Ship Evation capabilities determine which ship shoots first.
Repairing ships does always cost resources.

There's still the possibily to implement a "retreat" of the attacker if he gets to much damage.
