### ISSUE TITLE
ship cargo

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#94]
I added 3 lasers, 1 crew module, 1 power module and 75 metal to my colony ship (80 storage)
the ship displayed it was loaded with 108/80, I was expecting 80/80 so I just assumed this was a bug. I did not check the contents.
on arrival I emptied the content onto the planet and noticed it had not transported 2 lasers :(
so I assume the crew module uses 30 storage but was somehow added before 2 of the lasers, weird.

**Comment by Skratti** [comment]
Modules do cost 1/5 of their production costs.
This is made to prevent a small vessel without cargo bay to quickly steal all ship modules from a planet.

If there is now easy way to show this rule to users, this feature has to be removed.
What about enhancing the tooltip:

-----------------------------
Laser I
Requires 5 storage
-----------------------------

**Comment by marcgfx** [comment]
tooltip info would be great. but there is also the issue that I managed to fill my ship with 108 worth of weight, despite only having 80 cargo space.

**Comment by Skratti** [comment]
Tooltip shows size, new transfer dialog seems towork fine now
