### ISSUE TITLE
neutral territory and tooltip

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#95]
I think it's a bad idea to have the movement cost being based on the field you are on and not the cost of the field you are going to. I moved into a nebula with cost 8 (as it worked). now I am stuck there for about 4 turns and cant get out... not cool!

**Comment by Skratti** [comment]
That would indeed be a bad idea.
Costs are calculated using the target field.
There seems to be another bug involved. Can you investigate this?

**Comment by marcgfx** [comment]
yes sorry, the issue has been found. it had nothing to do with the nebula. I was trying to enter neutral territory, that I was not aware of not being able to enter. maybe you should give some mouse over information for territory that can not be entered due to ally/political reasons. I think the yellow dot might be meant for that.

**Comment by Skratti** [comment]
Good idea, this should be shown in the tooltip.

I'll also open a discussion about nebula movement points and borders in the forum

**Comment by Skratti** [comment]
Part of the tooltip issue
