### ISSUE TITLE
cargo transfer system

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#97]
as you are aware this menu is pretty horrible.
- it would be nice to be able to transfer goods without closing the window
- default target on the right should be the planet (it often happens that if you are not careful, other ships or planetary defense gets loaded with goods)
- >> button on every type of good on the left (and opposite on the right) would be useful. if I want to transfer all metal, I just press >>

**Comment by Skratti** [comment]
Implemented
