### ISSUE TITLE
refitting ships

### ISSUE THREAD

**Issue by marcgfx** [Skratti/EmpiresInSpace#98]
I think refitting ships should be quicker, e.g. one round and you should not lose all your movement points. currently refitting actually means 4 rounds of defenselessness and a lot more rounds of forced idle. 
I also don't think refitting and repairing should be the same thing, it's really not obvious.

suggestions: 
- additional button for repairing/stop repairing. 
- repair 10% per round
- don't make the ship entirely defenseless, but give it a disadvantage if it gets attacked (e.g. attacker goes first, instead of defender, or even 50% damage/evasion loss)
- refitting can take 5 rounds, but release it with full movement points. or at least let the engines be charged for 4 rounds

**Comment by Skratti** [comment]
Reparing does now need resources and being over a colony (that of an alliance member suffices).
Refitting does still set movement points to 0 and makes the ship vulnerable for 4 turns, but the ship does now regain it's movement points during those 4 turns.
